---
train:
  params:
    batch_size: 64
    epoch: 40
    lr: 0.0001
    decay: 1
    decay_step: 70000
    loss: MSELoss
  save:
    save_path: "F:\\Gazedataset"
    model_name: RT
    step: 5
  data:
    image: "F:\\Gazedataset\\MPIIGaze\\Image"
    label: "F:\\Gazedataset\\MPIIGaze\\Label"
  pretrains: "None"
test:
   load:
      begin_step: 5
      end_step: 40
      steps: 5
      load_path: "F:\\Gazedataset"
      model_name: RT
   data:
      image: "F:\\Gazedataset\\MPIIGaze\\Image"
      label: "F:\\Gazedataset\\MPIIGaze\\Label"
reader: reader_mpii
